version: '1'
services:
  backend:
    build:
      context: ./ivy
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    env_file:
      - ./ivy/.env
    restart: always
  frontend:
    build:
      context: ./zeal
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: always
  db:
    image: postgres:14-alpine
    env_file:
      - ./ivy/.env
    ports:
      - "5432:5432"
